from turtle import *
setup()
colormode(255)
setup( width = 1080, height = 650, startx = None, starty = None)

heart_turtle = Turtle()
top_turtle = Turtle()
item_turtle = Turtle()
map_turtle = Turtle()
ground_turtle = Turtle()
wall_turtle = Turtle()

def draw_hearts():
    heart_turtle.speed(9)
    heart_turtle.penup()
    heart_turtle.left(90)
    heart_turtle.forward(260)
    heart_turtle.right(90)
    heart_turtle.forward(290)
    heart_turtle.right(180)
    heart_turtle.pendown()
    for i in range(3):
        heart_turtle.color("black", "red")
        heart_turtle.begin_fill()
        heart_turtle.forward(15)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(15)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(20)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(20)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.left(90)
        heart_turtle.forward(5)
        heart_turtle.right(90)
        heart_turtle.forward(5)
        heart_turtle.end_fill()
        heart_turtle.right(90)
        heart_turtle.penup()
        heart_turtle.forward(60)
        heart_turtle.right(180)
        heart_turtle.pendown()

def top():
    top_turtle.color("black", "black")
    top_turtle.penup()
    top_turtle.left(90)
    top_turtle.forward(190)
    top_turtle.pendown()
    top_turtle.begin_fill()
    top_turtle.right(90)
    top_turtle.forward(540)
    top_turtle.left(90)
    top_turtle.forward(300)
    top_turtle.left(90)
    top_turtle.forward(1080)
    top_turtle.left(90)
    top_turtle.forward(300)
    top_turtle.left(90)
    top_turtle.forward(540)
    top_turtle.end_fill()

def ground():
    ground_turtle.color((255, 211, 172), (255, 211, 172))
    ground_turtle.penup()
    ground_turtle.left(90)
    ground_turtle.forward(190)
    ground_turtle.pendown()
    ground_turtle.right(90)
    ground_turtle.begin_fill()
    ground_turtle.forward(540)
    ground_turtle.right(90)
    ground_turtle.forward(600)
    ground_turtle.right(90)
    ground_turtle.forward(1080)
    ground_turtle.right(90)
    ground_turtle.forward(600)
    ground_turtle.right(90)
    ground_turtle.forward(540)
    ground_turtle.end_fill()

def draw_items():
    item_turtle.color("blue", "black")
    item_turtle.left(90)
    item_turtle.penup()
    item_turtle.forward(210)
    item_turtle.pendown()
    item_turtle.right(90)
    item_turtle.forward(50)
    item_turtle.left(90)
    item_turtle.forward(80)
    item_turtle.left(90)
    item_turtle.forward(50)
    item_turtle.left(90)
    item_turtle.forward(80)
    item_turtle.left(90)
    item_turtle.penup()
    item_turtle.forward(90)
    item_turtle.pendown()
    item_turtle.forward(50)
    item_turtle.left(90)
    item_turtle.forward(80)
    item_turtle.left(90)
    item_turtle.forward(50)
    item_turtle.left(90)
    item_turtle.forward(80)
    
def draw_map():
    map_turtle.color("gray", "gray")
    map_turtle.left(90)
    map_turtle.penup()
    map_turtle.forward(200)
    map_turtle.left(90)
    map_turtle.forward(130)
    map_turtle.pendown()
    ##################
    map_turtle.right(90)
    map_turtle.begin_fill()
    map_turtle.forward(110)
    map_turtle.left(90)
    map_turtle.forward(230)
    map_turtle.left(90)
    map_turtle.forward(110)
    map_turtle.left(90)
    map_turtle.forward(230)
    map_turtle.end_fill()

def draw_walls():
    wall_turtle.color(101, 217, 72)
    wall_turtle.left(90)
    wall_turtle.penup()
    wall_turtle.forward(190)
    wall_turtle.left(90)
    wall_turtle.forward(100)
    ######################
    wall_turtle.pendown()
    wall_turtle.left(90)
    wall_turtle.begin_fill()
    wall_turtle.forward(70)
    wall_turtle.right(45)
    wall_turtle.forward(20)
    wall_turtle.left(45)
    wall_turtle.forward(20)
    wall_turtle.right(90)
    wall_turtle.forward(200)
    wall_turtle.left(90)
    wall_turtle.forward(20)
    wall_turtle.right(45)
    wall_turtle.forward(20)
    wall_turtle.left(45)
    wall_turtle.forward(20)
    wall_turtle.right(45)
    wall_turtle.forward(20)
    wall_turtle.left(45)
    wall_turtle.forward(20)
    wall_turtle.right(45)
    wall_turtle.forward(20)
    wall_turtle.left(45)
    wall_turtle.forward(20)
    wall_turtle.right(45)
    wall_turtle.forward(20)
    wall_turtle.right(45)
    wall_turtle.forward(170)
    wall_turtle.right(90)
    wall_turtle.forward(241)
    wall_turtle.right(90)
    wall_turtle.forward(450)
    wall_turtle.end_fill()
    wall_turtle.penup()
    wall_turtle.forward(100)
    wall_turtle.right(90)
    wall_turtle.pendown()
    wall_turtle.forward(300)
    wall_turtle.left(45)
    wall_turtle.forward(20)
    wall_turtle.right(45)
    wall_turtle.forward(20)
    wall_turtle.left(90)
    wall_turtle.forward(520)
    wall_turtle.left(90)
    wall_turtle.forward(340)
    wall_turtle.left(40)
    forward

#top()
ground()
#draw_items()
#draw_map()
#draw_hearts()
draw_walls()



done()
